server:
  address: 0.0.0.0:8080
backend:
  storage: sqlite
kubernetes:
  server: https://192.168.100.2:6443
  frontProxyClientCert: /etc/kubernetes/pki/front-proxy-client.crt
  frontProxyClientKey: /etc/kubernetes/pki/front-proxy-client.key
  caCert: /etc/kubernetes/pki/ca.crt
