# permissions for end users to edit tokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: token-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kaustar
    app.kubernetes.io/part-of: kaustar
    app.kubernetes.io/managed-by: kustomize
  name: token-editor-role
rules:
- apiGroups:
  - authentication.kaustar.github.io
  resources:
  - tokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - authentication.kaustar.github.io
  resources:
  - tokens/status
  verbs:
  - get
