// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateUser implements createUser operation.
	//
	// Create a new user.
	//
	// POST /users
	CreateUser(ctx context.Context, req *UserCreateRequest) (*User, error)
	// ListUsers implements listUsers operation.
	//
	// List users.
	//
	// GET /users
	ListUsers(ctx context.Context, params ListUsersParams) (*UserList, error)
	// Whoami implements whoami operation.
	//
	// Get the current user.
	//
	// GET /whoami
	Whoami(ctx context.Context) (*User, error)
	// NewError creates *MessageStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *MessageStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
